export const DATA_FILLING ="DATA_FILLING";
export const HAS_CONFLICTS ="HAS_CONFLICTS";
export const VERIFICATION_ALLOWED ="VERIFICATION_ALLOWED";
export const SENT_INCONSISTENCY ="SENT_INCONSISTENCY";
export const  DATA_FILLED = "DATA_FILLED";
