ALTER TABLE good ADD COLUMN price NUMERIC(10,2);
ALTER TABLE tth DROP COLUMN goods_cost;

ALTER TABLE stock ADD COLUMN city VARCHAR(100);
ALTER TABLE stock ADD COLUMN street VARCHAR(100);
ALTER TABLE stock ADD COLUMN house VARCHAR(100);

