export const REGISTERED = "REGISTERED";
export const VERIFICATION_COMPLETED ="VERIFICATION_COMPLETED";
export const REGISTRATION_COMPLETED = "REGISTRATION_COMPLETED";
export const RELEASE_ALLOWED = "RELEASE_ALLOWED";
