logging:
  level:
    liquibase: INFO
    org.springframework.web: ERROR
spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath:/db/changelog-master.yml
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
      database: POSTGRESQL
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stock_app
    username: stock_dev
    password: njiokm
  main:
    allow-bean-definition-overriding: true
app:
  jwtSecret: crfbrflzldtlmytlfhjvvjcrdfcgfktyyfzgjfhjvahfywepejnnlfyfdtlmskbcdfnrbtdstlfujdjhzntotrfrbtytlfhjvgjvybndczhjccbzghjltym
  jwtExpirationInMs : 3600000
